### ISSUE TITLE
Summary displays: Delete not functional

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#24]
Selecting the delete icon on any summary display now displays the selected record, not the delete dialogue:

![screen shot 2017-11-17 at 12 57 04 pm](https://user-images.githubusercontent.com/329768/32961580-16d4995c-cb97-11e7-9e49-24d617e60cf9.png)

**Comment by scloo** [comment]
Code is broken with error:

Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
  at new HouseholdLocationSelectorView (<anonymous>:1747:37)
  at eval (coffeescript:8:1)
  at Object.CoffeeScript.eval (http://localhost:8089/js-libraries/coffee-script.js:12:5190)
  at Question.<anonymous> (http://localhost:8089/bundle.js:3304:38)
  at Function.each (http://localhost:8089/bundle.js:42395:19)
  at jQuery.fn.init.each (http://localhost:8089/bundle.js:42167:17)
  at QuestionView.render (http://localhost:8089/bundle.js:3297:36)
  at QuestionView.render (http://localhost:8089/bundle.js:3117:57)
  at success (http://localhost:8089/bundle.js:1003:38)
  at Object.options.success (http://localhost:8089/bundle.js:7769:30)
  at callback (http://localhost:8089/bundle.js:7059:43)
  at http://localhost:8089/bundle.js:90406:7
  at <anonymous>:null:null

**Comment by gmcressman** [comment]
This is working now, but I'm leaving this open for retesting after we've resolved other issues.

**Comment by gmcressman** [comment]
Tested. Fixed.
